### ISSUE TITLE
Add license to the repo

### ISSUE THREAD

**Issue by ORippler** [hmichaeli/alias_free_convnets#2]
Would you mind adding a license to your repo, so it is clear under which conditions the code and models can be used?

**Comment by hmichaeli** [comment]
I apologize for the delayed response. 
The majority of the code in the repository is based on [ConvNeXt](https://github.com/facebookresearch/ConvNeXt), which is protected under the MIT License. However, the repository also includes additional modules sourced from other projects ([BlurPool](https://github.com/adobe/antialiased-cnns), [APSPool](https://github.com/achaman2/truly_shift_invariant_cnns), [spatial-pytorch](https://github.com/MadryLab/spatial-pytorch)) that are protected under different licenses. 
Due to the presence of these different licenses, I am currently unable to license the repository as a whole.
